version: '3.9'

services:
  client:
    container_name: "rkt_client"
    build:
      context: ./packages/client
      dockerfile: Dockerfile.dev
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye

    volumes:
      - type: bind
        source: ./packages/client
        target: /app

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
    command: >
      sh -c "cd /app && yarn start"

    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  server:
    container_name: "rkt_server"
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye

    volumes:
      - type: bind
        source: ./packages/server
        target: /app

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
    command: >
      sh -c "cd /app && yarn start"

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    # links:
      # - postgres

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    container_name: "rkt_db"
    image: postgres:latest
    # image: "mdillon/postgis:9.6"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  adminer:
    container_name: "rkt_db_manager"
    image: adminer:latest
    restart: always
    ports:
      - "${DB_ADMINER_PORT}:${DB_ADMINER_PORT}"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: lucas-sandery

volumes:
  postgres-data:
