# vim: filetype=bash

BASE_URL := 'http://localhost:6000/'
STAGING_SERVER_01_BASE_URL := 'https://server-name/base/api/'
STAGING_BASE_URL := 'https://subdomain.domain.com/base/api/'

# Used to fix just rest calls if on nonmac
to_sed:
  sed -E -i'' 's/\bgsed\b/sed/g' ./rest.bash;
  sed -E -i'' 's/\bgsed\b/sed/g' ./auth.bash;

# Used to fix just rest calls if on mac
to_gsed:
  gsed -E -i'' 's/\bsed\b/gsed/g' ./rest.bash;
  gsed -E -i'' 's/\bsed\b/gsed/g' ./auth.bash;

post DATA AUTH ENDPOINT EXTRA_HEADERS='' QUERY_PARAMS='' FILETYPE='json' CONTENT_TYPE='application/json':
  #!/usr/bin/env bash
  set -euo pipefail
  . ./rest.bash;
  query_params='{{QUERY_PARAMS}}';
  [[ -e "$query_params" ]] && { query_params=`cat "$query_params"`; }
  [[ ! "$query_params" == "?"* ]] && { query_params=`echo "${query_params:+"?$query_params"}"`; }
  extra_headers='{{EXTRA_HEADERS}}';
  [[ -e "$extra_headers" ]] && { extra_headers=`cat "$extra_headers"`; }
  url="{{BASE_URL}}{{ENDPOINT}}$query_params";
  rest_post "$url" '{{DATA}}' '' '{{AUTH}}' '{{FILETYPE}}' '{{CONTENT_TYPE}}' "-H 'userId: 1'" '';

put DATA AUTH ENDPOINT EXTRA_HEADERS='' QUERY_PARAMS='' FILETYPE='json' CONTENT_TYPE='application/json':
  #!/usr/bin/env bash
  set -euo pipefail
  . ./rest.bash;
  query_params='{{QUERY_PARAMS}}';
  [[ -e "$query_params" ]] && { query_params=`cat "$query_params"`; }
  [[ ! "$query_params" == "?"* ]] && { query_params=`echo "${query_params:+"?$query_params"}"`; }
  extra_headers='{{EXTRA_HEADERS}}';
  [[ -e "$extra_headers" ]] && { extra_headers=`cat "$extra_headers"`; }
  url="{{BASE_URL}}{{ENDPOINT}}$query_params";
  rest_put "$url" '{{DATA}}' '' '{{AUTH}}' '{{FILETYPE}}' '{{CONTENT_TYPE}}' "-H 'userId: 1'" '';

get AUTH ENDPOINT EXTRA_HEADERS='' QUERY_PARAMS='' FILETYPE='json':
  #!/usr/bin/env bash
  set -euo pipefail
  . ./rest.bash;
  query_params='{{QUERY_PARAMS}}';
  [[ -e "$query_params" ]] && { query_params=`cat "$query_params"`; }
  [[ ! "$query_params" == "?"* ]] && { query_params=`echo "${query_params:+"?$query_params"}"`; }
  extra_headers='{{EXTRA_HEADERS}}';
  [[ -e "$extra_headers" ]] && { extra_headers=`cat "$extra_headers"`; }
  url="{{BASE_URL}}{{ENDPOINT}}$query_params";
  rest_get "$url" '' '' '{{AUTH}}' '{{FILETYPE}}' '' "-H 'userId: 1'" '';

get-movies-search QUERY_PARAMS='':
  #!/usr/bin/env bash
  . ./auth.bash;
  just get "`just_get_auth_token`" "movies/search" "{{QUERY_PARAMS}}";

get-movies:
  #!/usr/bin/env bash
  . ./auth.bash;
  just get "`just_get_auth_token`" "movies";

post-movie DATA:
  #!/usr/bin/env bash
  . ./auth.bash;
  just post "{{DATA}}" "`just_get_auth_token`" "movies";

put-movie DATA:
  #!/usr/bin/env bash
  . ./auth.bash;
  just put "{{DATA}}" "`just_get_auth_token`" "movies";

put-movie-status ID STATUS:
  #!/usr/bin/env bash
  . ./auth.bash;
  just put "" "`just_get_auth_token`" "movie/{{ID}}/{{STATUS}}";

